#!/usr/bin/env python3
"""
Encode variant images to latent tensors using VAE (Step 2 with DDP).

This script loads variant images generated by generate_variants_and_anchors.py
and encodes them to latent tensors using a VAE encoder.

Uses PyTorch DDP (DistributedDataParallel) for multi-GPU processing.

Output:
    - Latent tensors saved in {manifest_root}/{dataset_type}/{output_dir}/
    - Metadata JSON with encoding statistics

Usage:
    # Single GPU
    python generate_latents_for_variants_and_anchors.py \
        --model-id black-forest-labs/FLUX.1-dev \
        --trainval-json ../trainval.json \
        --split train \
        --output-dir ./output \
        --num-variations 5
    
    # Multi-GPU with torchrun
    torchrun --nproc_per_node=4 generate_latents_for_variants_and_anchors.py \
        --model-id black-forest-labs/FLUX.1-dev \
        --trainval-json ../trainval.json \
        --split train \
        --output-dir ./output \
        --num-variations 5
"""

import argparse
import json
import os
import shutil
from pathlib import Path
from typing import Dict, List, Optional
import time

import numpy as np
import torch
import torch.nn as nn
import torch.distributed as dist
from torch.utils.data import Dataset, DataLoader
from torch.utils.data.distributed import DistributedSampler
import cv2
from tqdm import tqdm

# Import diffusers for VAE loading
from diffusers import FluxPipeline

# Import project utilities
from _train_helpers import load_manifest_pairs, srgb01_to_m11


class VariantImageDataset(Dataset):
    """
    Dataset for loading variant images from disk for VAE encoding.
    
    Loads variant images generated by generate_variants_and_anchors.py
    and prepares them for batch encoding.
    
    Each sample contains:
    - Anchor sRGB image
    - Anchor XYZ image (optional)
    - N variant sRGB images
    - Metadata (basename, dataset_type) for saving
    """
    
    def __init__(
        self,
        manifest_path: Path,
        split: str = "train",
        dataset_subsets: Optional[List[str]] = None,
        num_variations: int = 5,
        generate_xyz_anchor: bool = False,
        resize_res: int = 1024,
        variant_dir_name: str = "anchor-variants-imgs",
        root_key: str = "root",
    ):
        self.manifest_path = manifest_path
        self.split = split
        self.num_variations = num_variations
        self.generate_xyz_anchor = generate_xyz_anchor
        self.resize_res = resize_res
        self.variant_dir_name = variant_dir_name
        
        # Load pairs from manifest
        pairs, self.meta = load_manifest_pairs(
            manifest_path,
            dataset_subsets=dataset_subsets,
            split=split,
            root_key=root_key,
        )
        
        # Filter to only pairs with existing variant images
        self.samples = []
        skipped = 0
        
        for srgb_path, xyz_path in pairs:
            basename = xyz_path.stem.replace("_xyz", "")
            variants_dir = xyz_path.parent.parent / self.variant_dir_name
            dataset_type = str(xyz_path.parts[-3])
            
            # Check required files
            anchor_srgb_path = variants_dir / f"{basename}_anchor_srgb.png"
            anchor_xyz_path = variants_dir / f"{basename}_anchor_xyz.png"
            
            # Handle different modes based on num_variations
            if num_variations == 0:
                # Anchor-only mode: only check anchor files
                var_paths = []
                files_to_check = [anchor_srgb_path]
                if generate_xyz_anchor:
                    files_to_check.append(anchor_xyz_path)
            else:
                # Variant mode: check anchor + variant files
                var_paths = [variants_dir / f"{basename}_var_{i:02d}_srgb.png" for i in range(num_variations)]
                files_to_check = [anchor_srgb_path] + var_paths
                if generate_xyz_anchor:
                    files_to_check.append(anchor_xyz_path)
            
            if all(p.exists() for p in files_to_check):
                self.samples.append({
                    "basename": basename,
                    "dataset_type": dataset_type,
                    "anchor_srgb_path": anchor_srgb_path,
                    "anchor_xyz_path": anchor_xyz_path if generate_xyz_anchor else None,
                    "var_paths": var_paths,
                })
            else:
                skipped += 1
        
        if skipped > 0:
            print(f"[WARN] Skipped {skipped} samples due to missing files")
        
        if not self.samples:
            if num_variations == 0:
                raise ValueError(f"No valid samples found with anchor images for split '{split}'")
            else:
                raise ValueError(f"No valid samples found with variant images for split '{split}'")
        
        if num_variations == 0:
            print(f"Loaded {len(self.samples)} samples with anchor images only for {split} split (anchor-only mode)")
        else:
            print(f"Loaded {len(self.samples)} samples with variant images for {split} split")
    
    def __len__(self) -> int:
        return len(self.samples)
    
    def __getitem__(self, idx: int) -> Dict:
        """Load all images for a single sample."""
        sample = self.samples[idx]
        
        # Load anchor sRGB
        anchor_srgb_img = self._load_image(sample["anchor_srgb_path"], bit_depth=8)
        anchor_srgb_tensor = torch.from_numpy(anchor_srgb_img).permute(2, 0, 1).float()
        
        # Load anchor XYZ if enabled
        # Always return a tensor to avoid None in collate; use empty tensor when disabled
        if self.generate_xyz_anchor and sample["anchor_xyz_path"] is not None:
            anchor_xyz_img = self._load_image(sample["anchor_xyz_path"], bit_depth=16)
            anchor_xyz_tensor = torch.from_numpy(anchor_xyz_img).permute(2, 0, 1).float()
        else:
            anchor_xyz_tensor = torch.empty(0)
        
        # Load variants (if any)
        if len(sample["var_paths"]) > 0:
            variant_tensors = []
            for var_path in sample["var_paths"]:
                var_img = self._load_image(var_path, bit_depth=8)
                var_tensor = torch.from_numpy(var_img).permute(2, 0, 1).float()
                variant_tensors.append(var_tensor)
            variants_stacked = torch.stack(variant_tensors, dim=0)  # [N, 3, H, W]
        else:
            # Anchor-only mode: return empty tensor for variants
            variants_stacked = torch.empty(0, 3, self.resize_res, self.resize_res)
        
        return {
            "anchor_srgb": anchor_srgb_tensor,
            "anchor_xyz": anchor_xyz_tensor,
            "variants": variants_stacked,
            "basename": sample["basename"],
            "dataset_type": sample["dataset_type"],
            "has_xyz": self.generate_xyz_anchor,
        }
    
    def _load_image(self, path: Path, bit_depth: int = 8) -> np.ndarray:
        """Load an image as an RGB (H, W, 3) float array in [0,1]."""
        if not path.exists():
            raise FileNotFoundError(f"Image file not found: {path}")
        
        img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
        if img is None:
            raise ValueError(f"Failed to load image: {path}")
        
        # Convert BGR to RGB
        if img.ndim == 3:
            img = img[:, :, ::-1]
        
        # Convert to [0,1] float based on bit depth
        if img.dtype == np.uint8:
            img = img.astype(np.float32) / 255.0
        elif img.dtype == np.uint16:
            img = img.astype(np.float32) / 65535.0
        else:
            img = img.astype(np.float32)
        
        # Validate image dimensions
        if img.ndim != 3 or img.shape[2] != 3:
            raise ValueError(f"Expected 3-channel RGB image, got shape: {img.shape}")
        
        # Resize if needed
        if img.shape[0] != self.resize_res or img.shape[1] != self.resize_res:
            img = cv2.resize(img, (self.resize_res, self.resize_res), interpolation=cv2.INTER_LANCZOS4)
        
        return img


def load_vae(model_id: str, device: torch.device) -> nn.Module:
    """Load the VAE from a FLUX pipeline onto the given device."""
    print(f"Loading VAE encoder for {model_id} on {device}...")

    if "FLUX" in model_id.upper():
        print(f"Loading full FluxPipeline to extract VAE...")
        pipe = FluxPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.bfloat16,
            device_map=None
        )
        vae = pipe.vae
        del pipe
        torch.cuda.empty_cache()
    else:
        raise ValueError(f"Unknown model type: {model_id}. Supported models: FLUX-dev, FLUX-Kontext-dev")

    vae = vae.to(device)
    vae.eval()
    
    print(f"VAE encoder loaded on {device}")
    return vae


def encode_and_save_batch(
    batch: Dict,
    vae: nn.Module,
    device: torch.device,
    output_dir: Path,
    manifest_root: str,
    model_name: str,
    rank: int,
) -> int:
    """Encode a batch of images, save the latents, and return the number of samples processed."""
    batch_size = len(batch["basename"])
    
    with torch.no_grad():
        # Prepare all images for encoding
        all_images = []
        
        # Add anchor sRGB images
        anchor_srgb = batch["anchor_srgb"].to(device, dtype=vae.dtype)
        all_images.append(anchor_srgb)
        
        # Add anchor XYZ images if present
        has_xyz = False
        if "has_xyz" in batch:
            try:
                has_xyz = bool(batch["has_xyz"][0].item())
            except Exception:
                has_xyz = bool(batch["has_xyz"][0])
        if not has_xyz and isinstance(batch.get("anchor_xyz", None), torch.Tensor):
            has_xyz = batch["anchor_xyz"].ndim == 4 and batch["anchor_xyz"].shape[1] == 3
        if has_xyz:
            anchor_xyz = batch["anchor_xyz"].to(device, dtype=vae.dtype)
            all_images.append(anchor_xyz)
        
        # Add variant images [B, N, 3, H, W] -> [B*N, 3, H, W] if present
        variants = batch["variants"]
        num_variations = variants.shape[1] if variants.ndim > 1 else 0
        
        if num_variations > 0:
            variants_flat = variants.view(-1, *variants.shape[2:]).to(device, dtype=vae.dtype)
            all_images.append(variants_flat)
        
        # Concatenate all images [B + B + B*N, 3, H, W] or [B + B*N, 3, H, W] or [B + B, 3, H, W] (anchor-only)
        all_images_tensor = torch.cat(all_images, dim=0)
        
        # Convert to [-1, 1] range for VAE
        all_images_tensor = srgb01_to_m11(all_images_tensor)
        
        # Encode all images in one batch
        latent_dist = vae.encode(all_images_tensor)
        latent_batch = latent_dist.latent_dist.mode()
        
        # Apply scaling factor if available (store scaled latents)
        if hasattr(vae.config, 'scaling_factor'):
            latent_batch = latent_batch * vae.config.scaling_factor
        
        if torch.isnan(latent_batch).any():
            nan_count = torch.isnan(latent_batch).sum().item()
            raise RuntimeError(
                f"[RANK {rank}] {nan_count}/{latent_batch.numel()} NaN values in encoded latents; "
                f"refusing to write a poisoned cache. basenames={list(batch['basename'])}")

        # Split latents back
        idx = 0
        anchor_srgb_latents = latent_batch[idx:idx+batch_size]
        idx += batch_size
        
        if has_xyz:
            anchor_xyz_latents = latent_batch[idx:idx+batch_size]
            idx += batch_size
        else:
            anchor_xyz_latents = None
        
        # Split variant latents only if num_variations > 0
        if num_variations > 0:
            variant_latents = latent_batch[idx:idx+batch_size*num_variations]
            variant_latents = variant_latents.view(batch_size, num_variations, *variant_latents.shape[1:])
        else:
            variant_latents = None
    
    # Save latents for each sample in batch
    for i in range(batch_size):
        basename = batch["basename"][i]
        dataset_type = batch["dataset_type"][i]
        
        output_dir_name = Path(str(output_dir)).name
        latent_dir = Path(manifest_root) / dataset_type / output_dir_name
        latent_dir.mkdir(parents=True, exist_ok=True)
        
        # Save anchor sRGB latent
        anchor_srgb_latent = anchor_srgb_latents[i].cpu()
        anchor_srgb_path = latent_dir / f"{basename}_anchor_srgb.pt"
        torch.save({
            "latent": anchor_srgb_latent,
            "metadata": {
                "type": "anchor_srgb",
                "model": model_name,
                "rank": rank,
                "timestamp": time.time(),
            }
        }, anchor_srgb_path)

        # Save anchor XYZ latent if present
        if has_xyz:
            anchor_xyz_latent = anchor_xyz_latents[i].cpu()
            anchor_xyz_path = latent_dir / f"{basename}_anchor_xyz.pt"
            torch.save({
                "latent": anchor_xyz_latent,
                "metadata": {
                    "type": "anchor_xyz",
                    "model": model_name,
                    "rank": rank,
                    "timestamp": time.time(),
                }
            }, anchor_xyz_path)

        # Save variant latents (only if num_variations > 0)
        if num_variations > 0 and variant_latents is not None:
            for j in range(num_variations):
                var_latent = variant_latents[i, j].cpu()
                var_path = latent_dir / f"{basename}_var_{j:02d}.pt"
                torch.save({
                    "latent": var_latent,
                    "metadata": {
                        "type": "varying",
                        "variation_idx": j,
                        "model": model_name,
                        "rank": rank,
                        "timestamp": time.time(),
                    }
                }, var_path)
    
    return batch_size


def build_argparser() -> argparse.ArgumentParser:
    """Build command line argument parser."""
    parser = argparse.ArgumentParser(
        description="Encode variant images to latent tensors using VAE (Step 2 with DDP)"
    )
    
    # Input parameters
    parser.add_argument("--trainval-json", type=Path, default="../trainval.json",
                       help="Path to trainval.json manifest")
    parser.add_argument("--split", type=str, default="all", choices=["train", "val", "test", "all"],
                       help="Dataset split to process")
    parser.add_argument("--datasets", type=str, nargs="+", default=None,
                       help="Dataset subsets to include (e.g., a5k raise nus)")
    parser.add_argument("--root-key", type=str, default="root",
                       help="Root key in manifest for dataset subsets (e.g., 'root' or 'root_aws')")
    
    # Model parameters
    parser.add_argument("--model-id", type=str, default="black-forest-labs/FLUX.1-dev",
                       help="Model ID for VAE loading (FLUX.1-dev / FLUX.1-Kontext-dev)")
    
    # Processing parameters
    parser.add_argument("--batch-size", type=int, default=8,
                       help="Batch size per GPU")
    parser.add_argument("--resize-res-for-batch-process", type=int, default=1024,
                       help="Resize resolution for batch processing (default: 1024)")
    parser.add_argument("--num-workers", type=int, default=4,
                       help="Number of data loader workers")
    
    # Output parameters
    parser.add_argument("--output-dir", type=Path, required=True,
                       help="Base output directory")
    parser.add_argument("--output-type", type=str, default="latent", choices=["latent"],
                       help="Output type (only latent supported)")
    
    # Settings
    parser.add_argument("--num-variations", type=int, default=5,
                       help="Number of variations per image (set to 0 for anchor-only mode)")
    parser.add_argument("--variant-dir-name", type=str, default="anchor-variants-imgs",
                       help="Subdirectory name containing anchor/variant images")
    parser.add_argument("--generate-xyz-anchor", action="store_true",
                       help="Encode XYZ anchor images in addition to sRGB anchors")
    parser.add_argument("--max-samples", type=int, default=None,
                       help="Maximum number of samples to process (for testing)")
    
    return parser


def main():
    """Main processing function with DDP."""
    args = build_argparser().parse_args()
    
    # Initialize DDP if using torchrun
    is_distributed = 'RANK' in os.environ and 'WORLD_SIZE' in os.environ
    
    if is_distributed:
        dist.init_process_group(backend='nccl')
        rank = dist.get_rank()
        world_size = dist.get_world_size()
        local_rank = int(os.environ['LOCAL_RANK'])
        device = torch.device(f'cuda:{local_rank}')
        torch.cuda.set_device(device)
    else:
        rank = 0
        world_size = 1
        local_rank = 0
        device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
    
    # Only rank 0 prints
    is_main = (rank == 0)
    
    if is_main:
        print(f"Distributed: {is_distributed}")
        print(f"World size: {world_size}")
        print(f"Processing split: {args.split}")
        print(f"Model ID: {args.model_id}")
        print(f"Batch size per GPU: {args.batch_size}")
        print(f"Number of variations: {args.num_variations}")
        print(f"Generate XYZ anchor: {args.generate_xyz_anchor}")
    
    # Validate arguments
    if not args.trainval_json.exists():
        raise FileNotFoundError(f"Manifest file not found: {args.trainval_json}")
    
    # Create dataset
    dataset = VariantImageDataset(
        manifest_path=args.trainval_json,
        split=args.split,
        dataset_subsets=args.datasets,
        num_variations=args.num_variations,
        generate_xyz_anchor=args.generate_xyz_anchor,
        resize_res=args.resize_res_for_batch_process,
        variant_dir_name=args.variant_dir_name,
        root_key=args.root_key,
    )
    
    # Limit samples if requested
    if args.max_samples is not None and args.max_samples < len(dataset):
        dataset.samples = dataset.samples[:args.max_samples]
        if is_main:
            print(f"Limited to {len(dataset.samples)} samples for testing")
    
    # Create sampler and dataloader
    if is_distributed:
        sampler = DistributedSampler(dataset, shuffle=False)
    else:
        sampler = None
    
    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        sampler=sampler,
        shuffle=False if is_distributed else False,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=False,
    )
    
    if is_main:
        print(f"Total samples: {len(dataset)}")
        print(f"Samples per rank: {len(dataloader.dataset) // world_size}")
        print(f"Batches per rank: {len(dataloader)}")
    
    # Load VAE
    vae = load_vae(args.model_id, device)
    
    # Determine model name
    if "FLUX" in args.model_id.upper():
        model_name = "FLUX"
    else:
        model_name = args.model_id.split("/")[-1]
    
    # Get manifest root
    manifest_root = dataset.meta.get("root", "")
    
    if is_distributed:
        dist.barrier()
    
    # Encode and save
    total_processed = 0
    # Track dataset types seen for metadata placement
    dataset_types_all = sorted({s["dataset_type"] for s in getattr(dataset, "samples", [])})
    
    if is_main:
        pbar = tqdm(total=len(dataloader), desc=f"Encoding (Rank {rank})", position=rank)
    
    for batch in dataloader:
        num_processed = encode_and_save_batch(
            batch=batch,
            vae=vae,
            device=device,
            output_dir=args.output_dir,
            manifest_root=manifest_root,
            model_name=model_name,
            rank=rank,
        )
        total_processed += num_processed
        
        if is_main:
            pbar.update(1)
    
    if is_main:
        pbar.close()
    
    # Gather statistics from all ranks
    if is_distributed:
        total_processed_tensor = torch.tensor([total_processed], device=device)
        dist.all_reduce(total_processed_tensor, op=dist.ReduceOp.SUM)
        total_processed_all = total_processed_tensor.item()
    else:
        total_processed_all = total_processed
    
    # Save metadata (only rank 0)
    if is_main:
        output_dir_name = Path(str(args.output_dir)).name
        metadata = {
            "model_id": args.model_id,
            "model_name": model_name,
            "split": args.split,
            "output_type": args.output_type,
            "num_variations": args.num_variations,
            "processing_config": {
                "world_size": world_size,
                "batch_size_per_gpu": args.batch_size,
                "num_workers": args.num_workers,
                "resize_res_for_batch_process": args.resize_res_for_batch_process,
                "generate_xyz_anchor": args.generate_xyz_anchor,
            },
            "output_paths": {
                "manifest_root": manifest_root,
                "latents_dir_pattern": "manifest_root / dataset_type / output_dir",
                "metadata_dir_pattern": "manifest_root / dataset_type / output_dir",
                "output_dir_name": output_dir_name,
            },
            "statistics": {
                "samples_encoded": total_processed_all,
                "srgb_latents_saved": total_processed_all * (1 + args.num_variations),
                "xyz_latents_saved": total_processed_all if args.generate_xyz_anchor else 0,
            },
            "timestamp": time.time(),
        }
        # Write one metadata file per dataset_type alongside its latents directory
        saved_metadata_paths = []
        meta_json_copied = []
        for dt in dataset_types_all:
            meta_dir = Path(manifest_root) / dt / output_dir_name
            meta_dir.mkdir(parents=True, exist_ok=True)
            metadata_path = meta_dir / f"step2_encoding_metadata_{args.split}.json"
            with open(metadata_path, "w") as f:
                json.dump(metadata, f, indent=2)
            saved_metadata_paths.append(str(metadata_path))
            
            # Copy meta.json from variant directory if it exists
            source_meta_json = Path(manifest_root) / dt / args.variant_dir_name / "meta.json"
            target_meta_json = meta_dir / "meta.json"
            if source_meta_json.exists():
                shutil.copy2(source_meta_json, target_meta_json)
                meta_json_copied.append(str(target_meta_json))
                if is_main:
                    print(f"Copied meta.json from {source_meta_json} to {target_meta_json}")
            else:
                if is_main:
                    print(f"[WARN] Source meta.json not found: {source_meta_json}")
                    print(f"       Expected at: {manifest_root} / {dt} / {args.variant_dir_name} / meta.json")

        print(f"\nEncoding complete!")
        print(f"  Samples encoded: {total_processed_all}")
        print(f"  sRGB latents saved: {total_processed_all * (1 + args.num_variations)}")
        if args.generate_xyz_anchor:
            print(f"  XYZ latents saved: {total_processed_all}")
        print(f"\nMetadata saved to:")
        for p in saved_metadata_paths:
            print(f"  - {p}")
        if meta_json_copied:
            print(f"\nCopied meta.json from {args.variant_dir_name} to:")
            for p in meta_json_copied:
                print(f"  - {p}")
        print(f"Output base dir (name used): {output_dir_name}")
        print(f"Manifest root: {manifest_root}")
    
    # Cleanup
    if is_distributed:
        dist.destroy_process_group()


if __name__ == "__main__":
    main()

